### ISSUE TITLE
Error on DashPlayer.react.js at chrome console

### ISSUE THREAD

**Issue by kirankotari** [plotly/dash-player#14]
Errors:
this.refs.player.getCurrentTime();
Uncaught TypeError: Cannot read property 'getCurrentTime' of undefined

this.refs.player.getSecondsLoaded();
Uncaught TypeError: Cannot read property 'getSecondsLoaded' of undefined

this.refs.player.getDuration();
Uncaught TypeError: Cannot read property 'getDuration' of undefined

pip list | grep dash
```
dash                               1.8.0
dash-core-components               1.7.0
dash-html-components               1.0.2
dash-player                        0.0.1
dash-renderer                      1.2.3
dash-table                         4.6.0
```

**Comment by alexshoe** [comment]
This error is not longer showing up in the latest builds of Dash Player. However, if do you run into it again, please do re-open this issue. Thanks!

**Comment by rk-servian** [comment]
@alexshoe 
This is still occurring. 
Console output from Chrome 
```
dash_player.v1_0_6m1677851916.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'getSecondsLoaded')
    at y.value (dash_player.v1_0_6m1677851916.min.js:1:111522)
value @ dash_player.v1_0_6m1677851916.min.js:1
4dash_player.v1_0_6m1677851916.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'getCurrentTime')
    at y.value (dash_player.v1_0_6m1677851916.min.js:1:111340)
value @ dash_player.v1_0_6m1677851916.min.js:1
dash_player.v1_0_6m1677851916.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'getDuration')
    at y.value (dash_player.v1_0_6m1677851916.min.js:1:111703)
value @ dash_player.v1_0_6m1677851916.min.js:1
```
