### ISSUE TITLE
Error at Chrome Console 

### ISSUE THREAD

**Issue by rk-servian** [plotly/dash-player#74]
#14 is still occurring on the latest version

```
dash_player.v1_0_6m1677851916.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'getSecondsLoaded')
    at y.value (dash_player.v1_0_6m1677851916.min.js:1:111522)
value @ dash_player.v1_0_6m1677851916.min.js:1
4dash_player.v1_0_6m1677851916.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'getCurrentTime')
    at y.value (dash_player.v1_0_6m1677851916.min.js:1:111340)
value @ dash_player.v1_0_6m1677851916.min.js:1
dash_player.v1_0_6m1677851916.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'getDuration')
    at y.value (dash_player.v1_0_6m1677851916.min.js:1:111703)
value @ dash_player.v1_0_6m1677851916.min.js:1
```

**Comment by alexcjohnson** [comment]
Thanks @rk-servian - can you provide a standalone app that reproduces this?

**Comment by rk-servian** [comment]
I noticed this during development phase for an internal/in-house project for an enterprise. Unfortunately not a public facing application. 
The console would be flooded with the messages as seen in the screenshot below
<img width="1431" alt="Screenshot 2023-03-07 at 6 12 38 PM" src="https://user-images.githubusercontent.com/78732892/223356233-a3dd8147-13cd-4c9d-a637-7c808d401a1e.png">

**Comment by alexcjohnson** [comment]
OK thanks. We won't be able to do anything until we're able to see the problem ourselves, and I don't see any such errors in for example https://dash.plotly.com/dash-player

I'll leave this issue open, hopefully at some point you or another visitor to this issue will be able to provide an app to reproduce the errors.

**Comment by mwelford-r1** [comment]
I have this same issue with an app I've been working on. For me, it seems to trigger in multipage dash apps when leaving a page with a dash-player component.

**Comment by mwelford-r1** [comment]
It appears that the solution to these errors is to add 
` componentWillUnmount(){
        clearInterval(this.handleCurrentTime);
        clearInterval(this.handleDuration);
        clearInterval(this.handleSecondsLoaded);
    }` to the DashPlayer.react.js file in the fragments folder.
